Dev
employee-performance-assessment/epa_backend pull request #19
Opened 2024-03-09 05:58 UTC by ValentinaBuddha

2024-03-11 08:52 UTC, nkorzh requested changes

2024-03-11 09:59 UTC, Bervy commented on src/main/java/ru/epa/epabackend/dto/task/TaskShortDto.java
> +public class TaskShortDto {
Краткую информацию, когда много тасок запрашивается, если одна то полная информация и входное ДТО

2024-03-11 10:01 UTC, Bervy commented on src/main/java/ru/epa/epabackend/dto/task/TaskFullDto.java
> +public class TaskFullDto {
Не совсем понял, файл называется TaskFullDto.java, класс TaskFullDto, где различия?

2024-03-15 06:37 UTC, JackobTheLion approved these changes

2024-03-15 06:38 UTC, BezuglovMikhail approved these changes

2024-03-15 06:52 UTC, merged