Add technology controller
employee-performance-assessment/epa_backend pull request #2
Opened 2024-02-25 13:48 UTC by hellotema90

2024-02-25 14:22 UTC, JackobTheLion commented
ПР нужно создавать не в main, а в dev. Можно отредактировать текущий ПР, не создавая новый.

2024-02-25 15:11 UTC, BezuglovMikhail approved these changes

2024-02-25 15:11 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/service/TechnologyService.java
> +    List<TechnologyDto> getAllTechnologys();
Добавь пустые строки между методами.

2024-02-25 15:11 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/service/TechnologyService.java
> +
Убери лишние пустые строки.

2024-02-25 15:26 UTC, JackobTheLion requested changes

2024-02-25 15:26 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/controller/TechnologyController.java
> +@RequestMapping(path = "/technologys")
Опечатка, верно technologies

2024-02-25 15:26 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/mapper/TechnologyMapper.java
> +public class TechnologyMapper {
Как насчет использовать MapStrtuct?

2024-02-25 15:26 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/mapper/TechnologyMapper.java
> +    public static TechnologyDto toTechnologyDto(Technology technology) {
лучше просто toDto

2024-02-25 15:26 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/mapper/TechnologyMapper.java
> +    public static Technology toTechnology(TechnologyDto technologyDto) {
а здесь toEntity

2024-02-25 15:26 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/TechnologyService.java
> +
Лишний энтер

2024-02-25 15:26 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/TechnologyService.java
> +    List<TechnologyDto> getAllTechnologys();
Опечатка, верно technologies

2024-02-25 15:26 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/TechnologyService.java
> +    TechnologyDto updateTechnology(TechnologyDto technologyDto, Long technologyId);
Тут принимаешь dto, а в create entity, лучше сделать единообразно и везде принимать dto

2024-02-25 15:26 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/TechnologyServiceImpl.java
> +    public List<TechnologyDto> getAllTechnologys(){
Опечатка, верно technologies

2024-02-25 15:26 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/TechnologyServiceImpl.java
> +        return TechnologyMapper.toTechnologyDto(technology);
А где сам update?

2024-02-25 15:26 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/TechnologyServiceImpl.java
> +    }
Для чего два метода с разными возвращаемыми значениями?

2024-02-25 15:26 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/TechnologyServiceImpl.java
> +
Лишний энтер

2024-02-25 15:26 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/TechnologyServiceImpl.java
> +        technologyRepository.deleteById(technologyId);
Может лучше заменить на soft delete?

2024-02-25 15:26 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/dto/TechnologyDto.java
> +@Builder
Я бы еще добавил @ToString

2024-02-25 15:26 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/TechnologyServiceImpl.java
> +                        (String.format("Технологии с id %d не существует", technologyId)));
Дублируется код, строка 39-41

2024-02-25 15:29 UTC, JackobTheLion commented
Повторюсь по поводу JavaDoc, на мой взгляд лучше писать даже там, где "все просто", потом будет гораздо проще разбираться, плюс это хорошо смотрится в портфолио и прививает нужные навыки написания документации

2024-02-25 16:40 UTC, hellotema90 commented on src/main/java/ru/epa/epabackend/service/TechnologyServiceImpl.java
> +
Почему?

2024-02-25 16:41 UTC, hellotema90 commented on src/main/java/ru/epa/epabackend/service/TechnologyServiceImpl.java
> +        technologyRepository.deleteById(technologyId);
Что ты имеешь ввиду?

2024-02-25 16:43 UTC, hellotema90 commented on src/main/java/ru/epa/epabackend/service/TechnologyServiceImpl.java
> +                        (String.format("Технологии с id %d не существует", technologyId)));
Все же смылс то разный

2024-02-25 16:49 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/TechnologyServiceImpl.java
> +        technologyRepository.deleteById(technologyId);
метод репозитория полностью удаляет запись из БД - это hard delete.
soft delete это пометка записи как удаленной, т.е. она все еще есть в базе, но не показывается при выгрузке.

2024-02-27 11:21 UTC, BezuglovMikhail requested changes

2024-02-27 11:21 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/controller/TechnologyController.java
> +    @GetMapping("/{technologyId}")
здесь должен быть аннотация @DeleteMapping

2024-02-27 11:28 UTC, BezuglovMikhail requested changes

2024-02-27 11:28 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/dto/TechnologyDto.java
> +
Лучше добавить отдельную DTO для создания, поле Id не нужно, так как  Id присваивается при добавлении технологии в БД.

2024-03-01 19:52 UTC, JackobTheLion reviewed
По хорошему нужно еще добавить мапинг в конфиг секьюрити, сейчас к твоему контроллеру не достучаться

2024-03-01 19:52 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/controller/TechnologyController.java
> +public class TechnologyController {
Нужно добавить аннотации свагера

2024-03-01 19:52 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/TechnologyServiceImpl.java
> +    public TechnologyDto createTechnology(Technology technology) {
Так и не поправил входной параметр. В update() ты принимаешь Dto, а тут сущность. Нужно сделать единообразно и принимать dto

2024-03-01 19:52 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/TechnologyServiceImpl.java
> +        return TechnologyMapper.toDto(getTechnologyById(technologyId));
А сам апдейт то где? :)

2024-03-02 06:56 UTC, JackobTheLion approved these changes

2024-03-03 12:01 UTC, BezuglovMikhail approved these changes

2024-03-03 12:23 UTC, merged