add auto logs:
employee-performance-assessment/epa_backend pull request #21
Opened 2024-03-10 13:44 UTC by hellotema90

org.springframework.web.servlet.DispatcherServlet
LogBook

2024-03-10 16:12 UTC, BezuglovMikhail requested changes
Ты не скачал изменения Владислава, он редактировал логику Task и добавил тест в постман, нужно сделать git pull  иначе ты затрешь его изменения.

2024-03-11 07:26 UTC, BezuglovMikhail approved these changes

2024-03-12 17:39 UTC, JackobTheLion requested changes

2024-03-12 17:39 UTC, JackobTheLion commented on pom.xml
> +            <groupId>org.zalando</groupId>
Проблема заландо в том, что он логирует ВООБЩЕ все, в т.ч. пароли:

> 2024-03-12T20:34:18.080+03:00 TRACE 17252 --- [nio-8080-exec-1] org.zalando.logbook.Logbook              : {"origin":"remote","type":"request","correlation":"84d12a154a75e95b","protocol":"HTTP/1.1","remote":"0:0:0:0:0:0:0:1","method":"POST","uri":"http://localhost:8080/public/register","host":"localhost","path":"/public/register","scheme":"http","port":"8080","headers":{"accept":["*/*"],"accept-encoding":["gzip, deflate, br"],"cache-control":["no-cache"],"connection":["keep-alive"],"content-length":["251"],"content-type":["application/json"],"host":["localhost:8080"],"postman-token":["820504b0-7e45-4a8b-93e5-8cca33d049b0"],"user-agent":["PostmanRuntime/7.30.0"]},"body":{"fullName":"George","nickName":"@igor","city":"Miami","email":"igor@yandex.ru",**"password":"ironman"**,"birthday":"2024-03-07","role":"ROLE_ADMIN","position":"general_director","department":"cybersecurity"}}

Можно как-то настроить, чтобы он пропускал или маскировал такие поля?

2024-03-13 21:48 UTC, JackobTheLion approved these changes

2024-03-13 21:51 UTC, merged