Employee
employee-performance-assessment/epa_backend pull request #3
Opened 2024-02-26 13:35 UTC by ValentinaBuddha

2024-02-26 14:07 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/dto/EmployeeDto.java
> +public class EmployeeDto {
Dto очень удобно разбивать на DtoRequest (то, что будет приходить к тебе) и DtoResponse (то, что ты будешь отдавать). Это позволит менять их независимо друг от друга и не будет фронтов в документации сбивать полями, которые тебе, скажем, в запросе не нужны, а отдавать ты их будешь

2024-02-26 14:08 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/model/Employee.java
>      private String nik;
лучше nickName

2024-02-26 14:11 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/EmployeeServiceImpl.java
> +        String nik = employeeDto.getNik();
здесь и далее: зачем создавать переменную? Можно сразу в ифе обращаться к полю employeeDto.getNik(), это не повлияет на производительность, но упростит чтение

2024-02-26 14:12 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/EmployeeServiceImpl.java
> +        if (nik != null && !nik.isBlank()) {
Все ифы предлагаю вынести в отдельный приватный метод updateEmployeeFileds(Employee oldEmployee, EmployeeDto employeeDto)

2024-02-26 14:13 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/EmployeeServiceImpl.java
> +    public void deleteEmployee(Long employeeId) {
@Transactional

2024-02-26 14:13 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/EmployeeServiceImpl.java
> +        employeeRepository.deleteById(employeeId);
Я бы сначала проверял, существует ли такой сотрудник, а то ты скажешь, что удалил сотрудника, которого нет и админ даже не узнает об ошибке

2024-02-26 14:14 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/EmployeeServiceImpl.java
> +                new EntityNotFoundException(String.format("Объект класса %s не найден", Employee.class)));
Поиск в базе по id повторяется несколько раз, лучше вынести в отдельный приватный метод

2024-02-26 14:14 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/EmployeeServiceImpl.java
> +    public EmployeeDto updateEmployee(Long employeeId, EmployeeDto employeeDto) {
@Transactional

2024-02-26 14:14 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/EmployeeServiceImpl.java
> +    public EmployeeDto addEmployee(EmployeeDto employeeDto) {
@Transactional

2024-02-26 14:16 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/controller/EmployeeControllerAdmin.java
> +@RequestMapping("admin/employees")
"/admin/employees"

2024-02-26 14:17 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/controller/EmployeeControllerPrivate.java
> +public class EmployeeControllerPrivate {
По-моему @Validated над классом тоже надо поставить

2024-02-26 14:19 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/dto/EmployeeDto.java
> +package ru.epa.epabackend.dto;
Потенциально у каждой сущности будет по несколько ДТО, чтобы было проще ориентироваться опять же можно создавать пакет под каждую группу ДТО: dto.employee

2024-02-26 14:21 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/dto/EmployeeDto.java
> +    private String nik;
лучше nickName

2024-02-26 14:22 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/util/Create.java
> +public interface Create {
лучше объединить с Update в единый класс:

```
import jakarta.validation.groups.Default;
    
    public interface ValidationGroups {
    
        interface Create extends Default {
        }
    
        interface Update extends Default {
        }
    }
```

2024-02-26 14:31 UTC, JackobTheLion requested changes

2024-02-26 14:31 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/exception/ErrorResponse.java
> +    private final String error;
Как насчет добавить поле DateTime?

2024-02-26 15:19 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/mapper/EmployeeMapper.java
> +@UtilityClass
Аннотация experimantal. Возможно стоит отказаться от нее и сделать методы статическими (если не используем MapStruct

> Current status: negative - Currently we feel this feature cannot move out of experimental status due to fundamental issues with non-star static imports.

https://projectlombok.org/features/experimental/UtilityClass

2024-02-27 07:40 UTC, ValentinaBuddha commented on src/main/java/ru/epa/epabackend/controller/EmployeeControllerAdmin.java
> +package ru.epa.epabackend.controller;
public не актуальна для нас - у нас будут только авторизованные пользователи
private не дают сделать - invalid package name. 
сделала user и admin

2024-02-27 08:05 UTC, ValentinaBuddha commented on src/main/java/ru/epa/epabackend/service/EmployeeServiceImpl.java
> +        String nik = employeeDto.getNik();
Во-первых потому что потом эта переменная используется два раза - это уже причина найти переменную.
Во-вторых, это читабельнее.

2024-02-27 08:06 UTC, ValentinaBuddha commented on src/main/java/ru/epa/epabackend/service/EmployeeServiceImpl.java
> +    public void deleteEmployee(Long employeeId) {
эта аннотация стоит над всем сервисом

2024-02-27 08:07 UTC, ValentinaBuddha commented on src/main/java/ru/epa/epabackend/service/EmployeeServiceImpl.java
> +    public EmployeeDto updateEmployee(Long employeeId, EmployeeDto employeeDto) {
эта аннотация стоит над всем сервисом

2024-02-27 08:08 UTC, ValentinaBuddha commented on src/main/java/ru/epa/epabackend/service/EmployeeServiceImpl.java
> +    public EmployeeDto addEmployee(EmployeeDto employeeDto) {
эта аннотация стоит над всем сервисом

2024-02-27 08:55 UTC, ValentinaBuddha commented on src/main/java/ru/epa/epabackend/mapper/EmployeeMapper.java
> +public class EmployeeMapper {
реализую в другой ветке позже

2024-02-27 08:55 UTC, ValentinaBuddha commented on src/main/java/ru/epa/epabackend/dto/EmployeeDto.java
> +    private String password;
реализую в другой ветке позже

2024-02-27 10:27 UTC, ValentinaBuddha commented on src/main/java/ru/epa/epabackend/exception/ErrorResponse.java
> +    private final String error;
скопировала из твоего проекта)

2024-02-27 10:28 UTC, ValentinaBuddha commented on src/main/java/ru/epa/epabackend/mapper/EmployeeMapper.java
> +@UtilityClass
реализую мапстракт позже в другой ветке

2024-02-27 11:21 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/EmployeeServiceImpl.java
> +                throw new WrongFullNameException("Поле ФИО должно состоять из трёх слов!");
А если меняют только фамилию?

2024-02-27 13:50 UTC, JackobTheLion approved these changes

2024-02-27 14:02 UTC, BezuglovMikhail approved these changes

2024-02-27 16:20 UTC, merged