fix: update entity
employee-performance-assessment/epa_backend pull request #37
Opened 2024-03-15 08:48 UTC by BezuglovMikhail

2024-03-15 10:26 UTC, ValentinaBuddha approved these changes

2024-03-15 11:09 UTC, JackobTheLion requested changes

2024-03-15 11:09 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeServiceImpl.java
> -            oldEmployee.setPassword(passwordEncoder.encode(password));
Вот эту строку в апдейт пользователя надо вернуть, иначе пароль не будет обновляться.

2024-03-15 11:09 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeServiceImpl.java
>          if (role != null) {
Роль, позиция и департамент теперь же в маппере обновляются? Можно удалить

2024-03-15 11:17 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeServiceImpl.java
> -            oldEmployee.setPassword(passwordEncoder.encode(password));
Может тогда убрать эту аннотацию: @Mapping(target = "password", ignore = true) 
И пароль будет обновляться в мапере, если он не пустой?

2024-03-15 11:19 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeServiceImpl.java
>          if (role != null) {
Убрал.

2024-03-15 11:25 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeServiceImpl.java
> -            oldEmployee.setPassword(passwordEncoder.encode(password));
Так нельзя, потому что перед сохранением в БД пароль надо шифровать, обрати внимание на `passwordEncoder.encode(password)`

2024-03-15 11:36 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeServiceImpl.java
> -            oldEmployee.setPassword(passwordEncoder.encode(password));
Понял. Исправил.

2024-03-15 11:47 UTC, JackobTheLion approved these changes

2024-03-17 05:08 UTC, merged

2024-03-19 13:27 UTC, nkorzh commented on src/main/java/ru/epa/epabackend/mapper/TaskMapper.java
> +    @Mapping(target = "executor", source = "executor")
а зачем вот эти 2 строчки?) кажется что он и сам так может

2024-03-19 13:27 UTC, nkorzh commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeServiceImpl.java
> +            oldEmployee.setPassword(passwordEncoder.encode(password));
кажется что если пароль кодируется здесь, то приложение уязвимо для man-in-the-middle атак
для быстрой разработки окей, но в общем случае надо делать как-то иначе
https://habr.com/ru/articles/594071/

2024-03-19 13:27 UTC, nkorzh commented on src/main/java/ru/epa/epabackend/service/impl/TechnologyServiceImpl.java
>      public Technology update(TechnologyRequestDto technologyDto, Long technologyId) {
кажется тут надо сохранить то что вы обновили

2024-03-20 06:03 UTC, Bervy commented on src/main/java/ru/epa/epabackend/mapper/TaskMapper.java
> +    @Mapping(target = "executor", source = "executor")
Удалил