Add postman tests technology
employee-performance-assessment/epa_backend pull request #42
Opened 2024-03-17 17:02 UTC by hellotema90

2024-03-18 18:27 UTC, OsipovKonstantin requested changes

2024-03-18 18:27 UTC, OsipovKonstantin commented on postman/epa_24_03_17.json
А ты добавлял тесты по технологиям? Почему-то текущие тесты не проходят, проверь, загрузил ли json с postman-тестами (которые тестил локально) в репозиторий

2024-03-18 19:18 UTC, hellotema90 commented on postman/epa_24_03_17.json
Поправил, почему-то их и правда не было

2024-03-18 19:25 UTC, OsipovKonstantin approved these changes

2024-03-19 05:58 UTC, JackobTheLion requested changes

2024-03-19 05:58 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeServiceImpl.java
> +    private void updateFields(Employee oldEmployee, EmployeeRequestDto employeeRequestDto) {
Зачем опять возвращать этот метод? Это теперь делается в маппере

2024-03-19 05:58 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeServiceImpl.java
> +        String position = employeeRequestDto.getPosition();
Все делается в маппере

2024-03-19 05:58 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java
> +    private void setNotNullParamToEntity(TaskRequestDto taskRequestDto, Task task) {
Нужно вынести в маппер

2024-03-19 05:58 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/config/LogbookConfiguration.java
> -                        "password",
Эти изменения ты уже вносил в другом ПР

2024-03-19 05:58 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/controller/admin/ProjectControllerAdmin.java
> +            description = "!!!Не предусмотрено текущим дизайном. " +
Про дизайн не нужно упоминать. Это потом путать будет. И вообще дизайн это вне нашей системы, не надо чтобы наш слой что-то знал о верхних слоях

2024-03-20 18:54 UTC, JackobTheLion requested changes

2024-03-20 18:54 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/mapper/EmployeeMapper.java
> +
Лишняя строка

2024-03-20 18:54 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/ProjectServiceImpl.java
> -        projectMapper.updateFields(projectUpdateRequestDto, project);
Обновлять поля сущности нужно маппером, метод нужно вернуть, а ручное обновление удалить

2024-03-20 18:54 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/TechnologyServiceImpl.java
> -        technologyMapper.updateFields(technologyDto, oldTechnology);
Аналогично: нужно вернуть метод маппера

2024-03-21 20:00 UTC, JackobTheLion approved these changes

2024-03-21 20:01 UTC, merged