Add evaluations
employee-performance-assessment/epa_backend pull request #46
Opened 2024-03-19 18:46 UTC by BezuglovMikhail

2024-03-20 19:45 UTC, OsipovKonstantin commented
Привет! Лучше влить изменения из текущего dev в свою ветку, чтобы не затереть то, что там сейчас есть. Там относительно много важных изменений произошло за последние 2-3 дня
![image](https://github.com/employee-performance-assessment/epa_backend/assets/98541812/3f0de8c6-c18b-4b0a-80ff-81efa9fb75a4)

2024-03-20 20:12 UTC, JackobTheLion requested changes

2024-03-20 20:12 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/mapper/EmployeeEvaluationMapper.java
> +    @Mapping(target = "appraiser", source = "appraiser")
Если названия полей одинаковые, то это прописывать не нужно, мапстракт сам поймет

2024-03-20 20:12 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/mapper/EmployeeEvaluationMapper.java
> +    default List<EmployeeEvaluationDto> mapList(List<EmployeeEvaluation> employeeEvaluations) {
Никита писал, что мапстракт умеет такое сам генерировать, можно реализацию не писать

2024-03-20 20:12 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/mapper/EvaluationMapper.java
> +    default List<EvaluationDto> mapList(List<Evaluation> evaluations) {
Никита писал, что мапстракт умеет такое сам генерировать, можно реализацию не писать

2024-03-21 08:09 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/model/Evaluation.java
> +public class Evaluation {
Да хорошо, поправлю.

2024-03-21 08:09 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/model/EmployeeEvaluation.java
> +    private Employee appraiser;
ок

2024-03-21 08:10 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/model/EmployeeEvaluation.java
> +    private Employee employee;
ок

2024-03-21 09:44 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/model/EmployeeEvaluation.java
> +    private Integer countStar;
Поправил.

2024-03-21 09:52 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
> +        LocalDate createDay = LocalDate.now();
Исправил.

2024-03-21 09:53 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/mapper/EmployeeEvaluationMapper.java
> +    @Mapping(target = "appraiser", source = "appraiser")
Исправил.

2024-03-21 10:00 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/mapper/EmployeeEvaluationMapper.java
> +    default List<EmployeeEvaluationDto> mapList(List<EmployeeEvaluation> employeeEvaluations) {
![image](https://github.com/employee-performance-assessment/epa_backend/assets/115709844/688f9429-628d-49cf-82fc-7e54ce0d8186)

2024-03-21 10:02 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/mapper/EmployeeEvaluationMapper.java
> +    default List<EmployeeEvaluationDto> mapList(List<EmployeeEvaluation> employeeEvaluations) {
Я заменил на:
List<EmployeeEvaluationDto> mapList(List<EmployeeEvaluation> employeeEvaluations);
если просто убрать  default метод, то программа не запускается.

2024-03-21 10:04 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/mapper/EvaluationMapper.java
> +    default List<EvaluationDto> mapList(List<Evaluation> evaluations) {
Заменил на:
List<CriteriaDto> mapList(List<Criteria> criteria);

2024-03-21 11:51 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
> +        return employeeEvaluationRepository.save(employeeEvaluationMapper
Исправил.

2024-03-21 20:06 UTC, JackobTheLion approved these changes

2024-03-21 20:06 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/util/StringPatterns.java
> +    public static final String CYRILIC_LATIN_ALPHABET_AND_NUMBERS = "^[a-zA-Zа-яА-ЯЁё0-9\\s\\-\\.\\,]+$";
Как это оказалось в твоем ПР?

2024-03-22 01:20 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/util/StringPatterns.java
> +    public static final String CYRILIC_LATIN_ALPHABET_AND_NUMBERS = "^[a-zA-Zа-яА-ЯЁё0-9\\s\\-\\.\\,]+$";
По просьбе Константина, я влил изменения из dev в свою ветку)

2024-03-23 03:30 UTC, nkorzh requested changes

2024-03-23 03:30 UTC, nkorzh commented on src/main/java/ru/epa/epabackend/controller/admin/CriteriaControllerAdmin.java
> +public class CriteriaControllerAdmin {
nit принято в конце названия класса указывать его роль, например `AdminCriteriaController`; ниже аналогично

2024-03-23 03:30 UTC, nkorzh commented on src/main/java/ru/epa/epabackend/controller/user/EmployeeEvaluationControllerUser.java
> +        return employeeEvaluationMapper.mapToDto(employeeEvaluationService.create(evaluatorId, evaluatedId, employeeEvaluationRequestDto));
nit однострочные конструкции будет тяжело читать вашим коллегам
```
var evaluation = employeeEvaluationService.create(evaluatorId, evaluatedId, employeeEvaluationRequestDto);
return employeeEvaluationMapper.mapToDto(evaluation);
```
вот так попроще

2024-03-23 03:30 UTC, nkorzh commented on src/main/java/ru/epa/epabackend/dto/evaluation/EmployeeEvaluationDto.java
> +public class EmployeeEvaluationDto {
это response или request? пришлось вчитаться в содержимое чтобы понять

2024-03-23 03:30 UTC, nkorzh commented on src/main/java/ru/epa/epabackend/service/impl/CriteriaServiceImpl.java
> +        Criteria criteria = criteriaRepository.findById(criteriaId).orElseThrow(() ->
nit: есть метод getById, он сам кидает исключение если сущность не найдена

2024-03-23 03:30 UTC, nkorzh commented on src/main/java/ru/epa/epabackend/service/impl/CriteriaServiceImpl.java
> +    public Criteria findById(Long criteriaId) {
в репозиториях метод find не кидает исключение, а get кидает
у вас наоборот – это сбивает с толку читателя

https://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/JpaRepository.html#getReferenceById(ID)

2024-03-23 03:30 UTC, nkorzh commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
> +        EmployeeEvaluation employeeEvaluation = employeeEvaluationRepository.findById(evaluationEvaluationId).orElseThrow(() ->
надо что-то сделать с форматированием: строчка очень длинная

2024-03-23 03:30 UTC, nkorzh commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
> +        if (employeeEvaluationRepository.existsById(evaluationEvaluationId)) {
если в репозитории метод delete сделать не void и int, он будет возвращать кол-во модифицированных записей
тогда можно не использовать existsById

2024-03-23 12:15 UTC, OsipovKonstantin approved these changes

2024-03-24 08:42 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/controller/admin/CriteriaControllerAdmin.java
> +public class CriteriaControllerAdmin {
Исправил

2024-03-24 08:52 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/controller/user/EmployeeEvaluationControllerUser.java
> +        return employeeEvaluationMapper.mapToDto(employeeEvaluationService.create(evaluatorId, evaluatedId, employeeEvaluationRequestDto));
Исправил.

2024-03-24 08:55 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/dto/evaluation/EmployeeEvaluationDto.java
> +public class EmployeeEvaluationDto {
Исправлю это замечание в следующем ПР с добавлением логики статистики по оценкам.

2024-03-24 09:03 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
> +        EmployeeEvaluation employeeEvaluation = employeeEvaluationRepository.findById(evaluationEvaluationId).orElseThrow(() ->
Исправил.

2024-03-24 09:38 UTC, merged