feat: create tasks
employee-performance-assessment/epa_backend pull request #5
Opened 2024-02-28 06:40 UTC by Bervy

Created TaskController, TaskService, TaskMapper, dto's for Task, Unit tests and Postman tests.

2024-02-28 11:01 UTC, JackobTheLion requested changes

2024-02-28 11:01 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/util/Utils.java
> +public class Utils {
Если класс утилитный, то его стоит сделать final и объявить приватный конструктор без полей, чтобы его экземпляр нельзя было создать.

2024-02-28 12:20 UTC, Bervy commented on src/main/java/ru/epa/epabackend/controller/task/admin/TaskAdminController.java
> +            @PathVariable Long taskId
Мне показалось, что так лучше читается. А так, поправлю.

2024-02-28 12:24 UTC, Bervy commented on src/main/java/ru/epa/epabackend/util/Constants.java
> +    public static final String DATE_TIME_STRING = "yyyy-MM-dd";
Да, я сделал коммит со своим классом констант и потом заметил, что уже был такой же и этот не удалил. Удалю.

2024-02-28 12:30 UTC, Bervy commented on src/main/java/ru/epa/epabackend/util/Utils.java
> +    public static void setNotNullParamToEntity(TaskInDto taskInDto, Task task, EmployeeRepository employeeRepository,
Хорошо

2024-02-28 12:31 UTC, Bervy commented on src/main/java/ru/epa/epabackend/exception/ErrorMessage.java
> +public class ErrorMessage {
Согласен, удалил.

2024-02-28 12:32 UTC, Bervy commented on src/main/java/ru/epa/epabackend/dto/TaskInDto.java
> +package ru.epa.epabackend.dto;
Создал

2024-02-28 12:37 UTC, Bervy commented on src/main/java/ru/epa/epabackend/exception/AccessDeniedException.java
> +public class AccessDeniedException extends RuntimeException {
Поправил

2024-02-28 12:39 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/task/admin/TaskAdminService.java
> +package ru.epa.epabackend.service.task.admin;
Тут не соглашусь, мне кажется удобней когда разбиты методы по пакетам и сервисам.

2024-02-28 12:44 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/task/admin/impl/TaskAdminServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException(EMPLOYEE_NOT_FOUND.getTitle()));
Сделал

2024-02-28 12:46 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/task/admin/TaskAdminService.java
> +public interface TaskAdminService {
Это тема для обсуждения)

2024-02-28 12:51 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/task/employee/impl/TaskEmployeeServiceImpl.java
> +    public TaskOutDto update(Long employeeId, Long taskId, TaskStatus taskStatus) {
Так пользователь кроме статуса ничего не может менять... Название метода согласен, поменял.

2024-02-28 12:53 UTC, Bervy commented on src/main/java/ru/epa/epabackend/controller/task/admin/TaskAdminController.java
> +package ru.epa.epabackend.controller.task.admin;
Сделал

2024-02-28 12:55 UTC, Bervy commented on src/main/java/ru/epa/epabackend/util/Utils.java
> +public class Utils {
Я его удалил, не нужен больше.

2024-02-28 13:07 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/task/admin/impl/TaskAdminServiceImpl.java
> +public class TaskAdminServiceImpl implements TaskAdminService {
Хотя один в один метод есть в сервисе пользователя. Может тогда если админ захочет посмотреть все задачи пользователя он обратится по API пользовательскому?

2024-02-28 13:09 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/task/admin/impl/TaskAdminServiceImpl.java
> +            task.setPoints(task.getBasicPoints() + days * task.getPenaltyPoints());
На счёт отдельного метода - вынесу. А вот сервис отдельный - надо обсудить.

2024-02-28 13:11 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/task/admin/TaskAdminService.java
> +package ru.epa.epabackend.service.task.admin;
А в чем смысл разбивать на два сервиса? Это затрудняет переиспользование кода, но не несет никаких преимуществ.

Пример:
У тебя в TaskEmployeeServiceImpl есть метод findAllByEmployeeId(Long employeeId), который возвращает список задач сотрудника, а что если администратор захочет сделать запрос? Дублировать код? Внедрять TaskEmployeeServiceImpl в TaskAdminController? 
Если в контроллерах грань четкая (разные эндпоинты), то в сервисах ее почти нет.
Или скажем метод findTaskById(Long id), понадобится он может и админу и сотруднику, куда его положить? Как с ним потом работать? Аналогично с остальными методами.

Если нужно разделить логику админа и пользователя то лучше отдельно создавать методы а-ля updateTaskByAdmin(Long idm TaskDto taskDto) внутри единого сервиса.

2024-02-28 13:12 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/task/admin/impl/TaskAdminServiceImpl.java
> +public class TaskAdminServiceImpl implements TaskAdminService {
Добавить метод - дублировать код. См. ветку о разделении сервисов.

2024-02-28 13:15 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/task/admin/impl/TaskAdminServiceImpl.java
> +public class TaskAdminServiceImpl implements TaskAdminService {
Не совсем понял тебя.

2024-02-28 13:21 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/task/admin/TaskAdminService.java
> +package ru.epa.epabackend.service.task.admin;
В случае с findTaskById(Long id) логика разная. Админ может просмотреть все задачи, а пользователь только ту задачу, в которой участвует. Давай обсудим это, если все будут за твоё решение, то я поправлю. Это не долго.

2024-02-28 13:26 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/task/admin/TaskAdminService.java
> +package ru.epa.epabackend.service.task.admin;
Логика будет отличаться только в проверке является ли пользователь админом или участником задачи. Запрос в базу и выбрасываемое исключение останутся такими же.
В крайнем случае лучше все равно разбить на два метода findTaskById(Long id) и findTaskByIdByAdmin(Long id), иначе тот, это упростит использование твоих сервисов.

2024-02-28 13:27 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/task/admin/impl/TaskAdminServiceImpl.java
> +public class TaskAdminServiceImpl implements TaskAdminService {
Сори, комментарий про API не прогрузился, когда я отвечал. :)

Если админ обращается по API пользователя, то он имеет к нему доступ, что совсем не обязательно будет так.

2024-02-29 06:37 UTC, Bervy commented on src/main/java/ru/epa/epabackend/util/TaskStatus.java
> +    public static Optional<TaskStatus> from(String stringStatus) {
Сделал

2024-02-29 06:42 UTC, Bervy commented on src/main/java/ru/epa/epabackend/dto/TaskOutDto.java
> +    private Employee creator;
Сделал

2024-02-29 06:42 UTC, Bervy commented on src/main/java/ru/epa/epabackend/dto/TaskOutDto.java
> +    private Employee executor;
Сделал

2024-02-29 06:45 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/task/admin/impl/TaskAdminServiceImpl.java
> +public class TaskAdminServiceImpl implements TaskAdminService {
"что совсем не обязательно будет так". Так и не понял, я думаю ничего страшного что админ может обратиться по пути пользователя, он же админ всё таки). А так если не договоримся, тогда в чате обсудим.

2024-02-29 06:48 UTC, Bervy commented on src/main/java/ru/epa/epabackend/dto/TaskOutDto.java
> +    private Project project;
Сделал

2024-02-29 09:14 UTC, Bervy commented on src/main/java/ru/epa/epabackend/util/DateConstant.java
> +    public static final DateTimeFormatter DATE_TIME_SPACE = DateTimeFormatter.ofPattern(DATE_PATTERN);
Я его удалил, думал пригодиться, но пока не нужен.

2024-02-29 09:15 UTC, Bervy commented on src/main/java/ru/epa/epabackend/controller/task/admin/TaskAdminController.java
> +    public List<TaskOutDto> findAllTasks() {
Вчера фронты сказали, что им всё нужно будет. Этот вопрос надо обсуждать.

2024-02-29 09:25 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/task/admin/impl/TaskAdminServiceImpl.java
> +    private Project getProjectFromRepositoryById(TaskInDto taskInDto) {
Сделал

2024-02-29 10:39 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/task/admin/TaskAdminService.java
> +public interface TaskAdminService {
Точно такое замечание выше, поэтому это я закрою.

2024-02-29 10:41 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/task/admin/impl/TaskAdminServiceImpl.java
> +    private Task getTaskFromRepositoryById(Long taskId) {
У меня есть публичный метод для получения таски по ид, этот вспомогательный для репозитория.

2024-02-29 19:14 UTC, Bervy commented on src/main/java/ru/epa/epabackend/controller/task/admin/TaskAdminController.java
> +    public List<TaskOutDto> findAllTasks() {
Сделал

2024-02-29 20:54 UTC, JackobTheLion approved these changes

2024-02-29 20:54 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/controller/admin/TaskControllerAdmin.java
> +@Tag(name = "Private: Задачи", description = "Закрытый API для работы с задачами")
У админов тэг Admin, см другие контроллеры

2024-02-29 20:54 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/mapper/ProjectMapper.java
> +@UtilityClass
Один маппер компонент, а другой UtilityClass, лучше сделать единообразно. Предпочтительно как компонент, т.к. потом в мапстракте это будет компонент

2024-02-29 21:00 UTC, Bervy commented on src/main/java/ru/epa/epabackend/mapper/ProjectMapper.java
> +@UtilityClass
Это маппер Константина, пусть он тогда уже сделает. Я его создал чисто, чтобы у меня заработало. Хорошо? Он еще не делал ПР

2024-02-29 21:03 UTC, Bervy commented on src/main/java/ru/epa/epabackend/controller/admin/TaskControllerAdmin.java
> +@Tag(name = "Private: Задачи", description = "Закрытый API для работы с задачами")
сделал

2024-03-01 05:24 UTC, merged