feat(unit test): add unit tests technology
employee-performance-assessment/epa_backend pull request #55
Opened 2024-03-24 18:50 UTC by hellotema90

2024-03-25 18:41 UTC, JackobTheLion approved these changes

2024-03-25 18:41 UTC, JackobTheLion commented on src/test/java/ru/epa/epabackend/task/technology/TechnologyUnitTests.java
> +    private TechnologyResponseDto technologyResponseDto = new TechnologyResponseDto();
Зачем это поле? ты же им не пользуешься

2024-03-25 18:41 UTC, JackobTheLion commented on src/test/java/ru/epa/epabackend/task/technology/TechnologyUnitTests.java
> +        assertNotNull(technology);
Проверка на null не нужна

2024-03-25 18:41 UTC, JackobTheLion commented on src/test/java/ru/epa/epabackend/task/technology/TechnologyUnitTests.java
> +        int expectedId = 1;
id - Long

2024-03-26 14:07 UTC, BezuglovMikhail approved these changes

2024-03-27 06:35 UTC, JackobTheLion requested changes

2024-03-27 06:35 UTC, JackobTheLion commented on src/test/java/ru/epa/epabackend/employeeEvaluation/EmployeeEvaluationUnitTests.java
> +    @Test
Закомментированного кода быть не должно

2024-03-30 14:15 UTC, JackobTheLion approved these changes

2024-03-30 22:08 UTC, merged