Feat analytics task
employee-performance-assessment/epa_backend pull request #57
Opened 2024-03-25 21:08 UTC by Bervy

2024-03-26 07:21 UTC, JackobTheLion reviewed
Лучше всю аналитику вынести в отдельный сервис, чтобы она не смешивалась с логикой других сервисов.
В целом очень много дублирования кода: например логика расчета долей по просроченным таскам повторяется 4 раза практически слово в слово. Лучше вынести в отдельный метод.
Еще раз пройдись по всем методам расчета, убедись что они работают, убедись, что ты не делаешь лишних действий.
В некоторых случаях возможно имеет смысл сделать два запроса к базе, например сначала все задачи выполненные в срок, а вторым все просроченные задачи.

2024-03-26 07:21 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java
> +        double totalNumbersOfTaskOfTeamCompleted = teamCompletedOnTime + teamNotCompletedOnTime;
Зачем это считать? есть tasks.size()

2024-03-26 07:21 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java
> +            return taskMapper.mapToAnalyticsDto(
Лучше это делать билдером, а не маппером

2024-03-26 07:21 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java
> +                task.getFinishDate().isAfter(startDate) &&
Зачем эта проверка?

2024-03-26 07:21 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java
> +                if (task.getFinishDate().isAfter(task.getDeadLine())) {
Ты только что это проверял в методе isFinishDateBetweenStartDateAndEndDate()

2024-03-26 07:41 UTC, Bervy commented on src/main/java/ru/epa/epabackend/controller/admin/TaskControllerAdmin.java
> +    public List<TaskShortResponseDto> findAll(Principal principal) {
Согласен, давай тут оставим. В будущем буду отдельный ПР для этого делать. Вроде по мелочи, но все равно)

2024-03-26 08:10 UTC, Bervy commented on src/main/java/ru/epa/epabackend/controller/admin/TaskControllerAdmin.java
> +            @RequestParam(name = "rangeStart") String rangeStart,
Поправил

2024-03-26 08:24 UTC, Bervy commented on src/main/java/ru/epa/epabackend/dto/task/TaskAnalyticsFullResponseDto.java
> +public class TaskAnalyticsFullResponseDto {
Тогда лучше может по аналогии со следующим замечанием сделать TeamAnalyticsFullResponseDto? У меня есть краткое ДТО только с процентами и полное - ещё и с лидерами.

2024-03-26 08:25 UTC, Bervy commented on src/main/java/ru/epa/epabackend/dto/employee/EmployeeShortAnalyticsResponseDto.java
> +public class EmployeeShortAnalyticsResponseDto {
Поменял

2024-03-26 08:26 UTC, ValentinaBuddha requested changes
В админском контроллере  в сервисе дублирующий код - лишний, надо удалить. Внутри методы по поиску аналитики не проверяла, может в сл раз проверю

2024-03-26 08:27 UTC, Bervy commented on src/main/java/ru/epa/epabackend/dto/task/TaskAnalyticsShortResponseDto.java
> +public class TaskAnalyticsShortResponseDto {
Поменял

2024-03-26 08:31 UTC, Bervy commented on src/main/java/ru/epa/epabackend/controller/admin/TaskControllerAdmin.java
> +        return taskService.findTeamStatisticsByAdmin(rangeStart, rangeEnd, principal.getName());
Так это же разные пути, админ по своему пути может одну информацию получить, а обычный сотрудник другую

2024-03-26 08:32 UTC, Bervy commented on src/main/java/ru/epa/epabackend/dto/task/TaskAnalyticsFullResponseDto.java
> +    private Double teamCompletedOnTimePercent;
Хорошо, я не против.

2024-03-26 08:32 UTC, Bervy commented on src/main/java/ru/epa/epabackend/dto/task/TaskAnalyticsShortResponseDto.java
> +    private Double teamCompletedOnTimePercent;
Хорошо, я не против.

2024-03-26 08:34 UTC, Bervy commented on src/main/java/ru/epa/epabackend/repository/TaskRepository.java
> +            "WHERE (NULLIF((:status), NULL) IS NULL OR t.status = :status)" +
Я знаю, работе это не мешает.

2024-03-26 08:53 UTC, Bervy commented on src/main/java/ru/epa/epabackend/dto/task/TaskAnalyticsFullResponseDto.java
> +    private Double teamCompletedOnTimePercent;
Между On time и In Time фактически нет разницы. Team убрал, так как и так теперь понятно, что team

2024-03-26 08:56 UTC, Bervy commented on src/main/java/ru/epa/epabackend/mapper/TaskMapper.java
> +    TaskAnalyticsFullResponseDto mapToAnalyticsDto(Double teamCompletedOnTimePercent,
Согласен, что-то я маппером увлёкся)

2024-03-26 10:40 UTC, Bervy commented on src/main/java/ru/epa/epabackend/util/DateConstant.java
> +    public static final DateTimeFormatter DATE_SPACE = DateTimeFormatter.ofPattern(DATE_PATTERN);
А как лучше? DATE_FORMATTER?

2024-03-26 10:42 UTC, Bervy commented on src/main/java/ru/epa/epabackend/repository/TaskRepository.java
> +    List<Task> findAllByOwnerId(Long employeeId, LocalDate startDate, LocalDate endDate);
Исправил

2024-03-26 10:46 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java
> +        double totalNumbersOfTaskOfTeamCompleted = teamCompletedOnTime + teamNotCompletedOnTime;
Так это же общее у всех сотрудников и за обоими циклами

2024-03-26 10:46 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java
> +            return taskMapper.mapToAnalyticsDto(
Сделал

2024-03-26 10:47 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java
> +                task.getFinishDate().isAfter(startDate) &&
Для того, чтобы понять входить ли дата окончания задачи в пределы в параметрах. Там где не нужно доставать сотрудников из репозитория employee я сразу запрос отправлял в task репозиторий. А тут надо еще проверку делать.

2024-03-26 10:48 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java
> +                if (task.getFinishDate().isAfter(task.getDeadLine())) {
В методе isFinishDateBetweenStartDateAndEndDate() я проверяю, что дата окончания находится в пределах стартой и окончательной даты пришедшей из фронта. А тут проверка, что финишная дата после дедлайна.

2024-03-26 10:50 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java
> +    private static final int PERCENTAGE_OF_TASKS_COMPLETED_ON_TIME = 50;
Объясни, почему именно туда? Эта константа же только к этому классу относится.

2024-03-26 10:50 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java
> +    public TaskAnalyticsFullResponseDto findTeamStatisticsByAdmin(String rangeStart, String rangeEnd, String email) {
Да, нашёл.

2024-03-26 11:41 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/dto/task/TaskAnalyticsFullResponseDto.java
> +    private Double teamCompletedOnTimePercent;
Комментарий касался в основном team, а что касается on time и in time то разница с точки зрения грамматики есть: in time может означать, что что-то произошло в срок или до него, on time точно в срок.
Я не настаиваю в переименовании, просто для информации.

2024-03-26 11:44 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java
> +    private static final int PERCENTAGE_OF_TASKS_COMPLETED_ON_TIME = 50;
Потому что если в какой-то момент мы захотим эту цифру поменять, то нужно будет пересобрать приложение, докер образ, залить и скачать на сервере. 
Если пробросить в properties, а оттуда брать значение из переменных окружения, то достаточно будет поменять настройку и перезапустить сервер. Как вариант можно указать значение по умолчанию, которое будет применяться, если в application.properties значение не присвоено. Почитай про `@Value`

2024-03-26 11:50 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/util/DateConstant.java
> +    public static final DateTimeFormatter DATE_SPACE = DateTimeFormatter.ofPattern(DATE_PATTERN);
Я бы назвал просто DATE_FORMATTER, причем тут SPACE я не понял, но вообще я не уверен, что он нужен, можно так:
```
String s = "2024-12-31";
LocalDateTime localDateTime = LocalDate.parse(s).atTime(0, 0);
```

2024-03-26 11:51 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java
> +        double totalNumbersOfTaskOfTeamCompleted = teamCompletedOnTime + teamNotCompletedOnTime;
teamCompletedOnTime + teamNotCompletedOnTime == tasks.size()
Считать дополнительно не нужно ничего

2024-03-26 12:03 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java
> +                task.getFinishDate().isAfter(startDate) &&
Тогда нужно переименовать метод, чтобы название показывало, что ты не корректность даты конца проверяешь, а что она попадает в период поиска, например: isFinishedWhininSearchPeriod()
И переменные тоже лучше переименовать, можно как в одном из твjих других методов rangeStart и rangeEnd

2024-03-26 12:30 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java
> +        double totalNumbersOfTaskOfTeamCompleted = teamCompletedOnTime + teamNotCompletedOnTime;
Я изменил там логику, теперь это не tasks.size. Я забыл сделать проход по всем сотрудникам и потом у них уже искать задачи

2024-03-26 12:40 UTC, Bervy commented on src/main/java/ru/epa/epabackend/util/DateConstant.java
> +    public static final DateTimeFormatter DATE_SPACE = DateTimeFormatter.ofPattern(DATE_PATTERN);
Сделал

2024-03-26 12:47 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java
> +                task.getFinishDate().isAfter(startDate) &&
Сделал

2024-03-27 07:05 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java
> +    private static final int PERCENTAGE_OF_TASKS_COMPLETED_ON_TIME = 50;
Сделал

2024-03-27 07:52 UTC, ValentinaBuddha commented on src/main/java/ru/epa/epabackend/controller/admin/TaskControllerAdmin.java
> +        return taskService.findTeamStatisticsByAdmin(rangeStart, rangeEnd, principal.getName());
Да ты прав, не увидела что методы возвращают разную информацию

2024-03-27 08:24 UTC, JackobTheLion requested changes

2024-03-27 08:24 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        double teamCompletedOnTime = 0;
Почему дабл? Ты его потом все равно к инту приводишь

2024-03-27 08:24 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    private IndividualAnalyticsResponseDto getIndividualDtoOfCompletedTasksWithinSearchPeriod(Employee employee,
Внутри сервисов работать с DTO не очень хорошая идея. Тут достаточно много расчетов поэтому в будущем ты, возможно, захочешь запросы кэшировать, при этом тебе могут понадобится доп поля. 
Лучше выделить отдельную сущность с которой ты будешь работать, пусть пока ее поля будут совпадать с ДТО, а в ДТО маппить в контроллере как обычно.

И сам метод можно назвать короче, например calcEmployeeStats(), что возвращает и по каким критериям определяет будет видно из вохдных параметров

2024-03-27 08:24 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    private int getPercentageOfOneNumberFromAnother(double number1, double number2) {
лучше calcPercent()

2024-03-27 08:24 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/AnalyticsService.java
> +    TeamAnalyticsFullResponseDto findTeamStatisticsByAdmin(LocalDate startDate, LocalDate endDate, String email);
Здесь и далее: find не совсем корректно, ты не ищешь, ты раcсчитываешь, лучше calc или get

2024-03-27 08:24 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        double teamCompletedOnTime = 0;
Опять же, зачем дабл?

2024-03-27 08:32 UTC, Bervy commented on src/main/resources/analytic.properties
> +percentage_of_tasks_completed_on_time = 80
Хорошо

2024-03-27 08:34 UTC, Bervy commented on src/main/java/ru/epa/epabackend/dto/analytics/IndividualAnalyticsResponseDto.java
> +    private Long id;
Тогда и для fullName и position надо employeeFullName, employeePosition?

2024-03-27 08:36 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/dto/analytics/IndividualAnalyticsResponseDto.java
> +    private Long id;
На твое усмотрение, меня с толку не сбило, такое поле у нас есть только у employee, а вот чей id я не сразу понял

2024-03-27 08:36 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        return new IndividualAnalyticsResponseDto();
Тогда надо перед возвратом делать проверку на null?

2024-03-27 08:37 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        double teamCompletedOnTime = 0;
Потому что при делении int на int я теряю число

2024-03-27 08:38 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    private int getPercentageOfOneNumberFromAnother(double number1, double number2) {
А это название говорит о том, что мы считаем процент одного числа от другого?

2024-03-27 08:40 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        return new IndividualAnalyticsResponseDto();
Ты и сейчас проверку делаешь, только id проверяешь внутри объекта

2024-03-27 08:41 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/AnalyticsService.java
> +    TeamAnalyticsFullResponseDto findTeamStatisticsByAdmin(LocalDate startDate, LocalDate endDate, String email);
Изменил

2024-03-27 08:41 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        double teamCompletedOnTime = 0;
Объяснил выше

2024-03-27 08:45 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    private int getPercentageOfOneNumberFromAnother(double number1, double number2) {
Это и так понятно по входным параметрам

2024-03-27 08:47 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    private IndividualAnalyticsResponseDto getIndividualDtoOfCompletedTasksWithinSearchPeriod(Employee employee,
Тогда получается будут 2 модели? IndividualAnalytics и TeamAnalytics, при чем эти модели не будут никак привязаны к базе данных , как остальные?

2024-03-27 08:49 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        for (Task task : employee.getTasks()) {
Да, я к сожалению не придумал запрос для этого. Можешь подсказать? Мне же надо делать по любому запрос в employee репозиторий и оттуда уже подтягивать нужные задачи у сотрудника.

2024-03-27 08:50 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    private IndividualAnalyticsResponseDto getIndividualDtoOfCompletedTasksWithinSearchPeriod(Employee employee,
Да, получается так

2024-03-27 08:50 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        return new IndividualAnalyticsResponseDto();
Я этот метод использую 2 раза, и в 1 случае мне не нужна эта проверка

2024-03-27 08:52 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    private int getPercentageOfOneNumberFromAnother(double number1, double number2) {
Ладно, ок

2024-03-27 08:53 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    private IndividualAnalyticsResponseDto getIndividualDtoOfCompletedTasksWithinSearchPeriod(Employee employee,
Я с этим не сталкивался. но разве модели не должны быть всегда привязаны к БД?

2024-03-27 08:54 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        for (Task task : employee.getTasks()) {
У тебя в любом случае два запрос: у коллекций по умолчанию FETCH.LAZY

Аналогичный метод уже есть, только в нем OwnerId
List<Task> findByExecutorIdAndFinishDateBetween(Long id, LocalDate startDate, LocalDate endDate);

2024-03-27 08:56 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    private IndividualAnalyticsResponseDto getIndividualDtoOfCompletedTasksWithinSearchPeriod(Employee employee,
А причем тут БД? Ты создаешь класс и работаешь с его объектами вот и все.

2024-03-27 08:57 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        for (Task task : employee.getTasks()) {
Так мне только задачи нужны, а тут именно сотрудники. Я же не буду по каждому сотруднику в цикле такой запрос в БД делать.

2024-03-27 08:58 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        return new IndividualAnalyticsResponseDto();
Да, только объект ты создаешь в любом случае, даже тогда, когда он тебе не нужен.

2024-03-27 09:07 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        for (Task task : employee.getTasks()) {
Так ты уже делаешь под капотом, только вытаскиваешь вообще все задачи, это плохо.
По поводу сотрудников я ен понял, ты из бд вытаскиваешь задачи сотрудников.

2024-03-27 09:08 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    private IndividualAnalyticsResponseDto getIndividualDtoOfCompletedTasksWithinSearchPeriod(Employee employee,
Понял, то есть по факту нам модели нужны для работы в сервисе? А ДТО в контроллерах?

2024-03-27 09:09 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        return new IndividualAnalyticsResponseDto();
Так что я буду возвращать фронту, если я буду null возвращать?

2024-03-27 09:10 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        double teamCompletedOnTime = 0;
Ну это решается просто перестановкой множителей: number1 * 100 / number2
int на мой взгляд лучше, т.к. он занимает меньше места и в этом случае это все таки счетчик, счетчик не может быть не целым числом, а ты как бы это допускаешь

2024-03-27 09:20 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        return new IndividualAnalyticsResponseDto();
null возвращать не надо, ты все верно написал, если из приватного метода возвращается null то надо вернуть пустой объект.
Разница в том, что ты создаешь объект только тогда, когда он нужен.

2024-03-27 09:20 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        double teamCompletedOnTime = 0;
Хорошо, изменил порядок

2024-03-27 09:23 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        for (Task task : employee.getTasks()) {
Я знаю, что вытаскиваю все задачи. И мне как-то надо придумать запрос, чтобы обращаться к репозиторию employee и вытаскивать оттуда сотрудников(id, fullName, position) и только те задачи, которые будут соответствовать критериям. Вот в этом затуп

2024-03-27 09:24 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    private IndividualAnalyticsResponseDto getIndividualDtoOfCompletedTasksWithinSearchPeriod(Employee employee,
Приблизительно так да.

Только не стоит приравнивать сущность к модели, это не одно и тоже
https://blog.skillfactory.ru/glossary/mvc/
https://ru.hexlet.io/blog/posts/chto-takoe-mvc-rasskazyvaem-prostymi-slovami

2024-03-27 09:24 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        return new IndividualAnalyticsResponseDto();
Не понимаю в чем разница? Что я в приватном методе создам пустой объект(когда нет задач) и верну его. Или я возвращу null в нём, потому сделаю проверку и все равно верну пустой объект.

2024-03-27 09:25 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        return new IndividualAnalyticsResponseDto();
Никаких лишних пустых объектов я не создаю

2024-03-27 09:25 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        for (Task task : employee.getTasks()) {
Почему к репозиторию сотрудников то? Есть же репозиторий задач

2024-03-27 09:27 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        return new IndividualAnalyticsResponseDto();
В том что здесь, если объект пустой, то ты его выбрасываешь, т.е. создал ты его зря.
```
            IndividualAnalyticsResponseDto individualAnalyticsResponseDto =
                    getIndividualDtoOfCompletedTasksWithinSearchPeriod(employee, rangeStart, rangeEnd);
            if (individualAnalyticsResponseDto.getId() != null) {
                employeesShortDto.add(individualAnalyticsResponseDto);
            }
```

2024-03-27 09:27 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    private IndividualAnalyticsResponseDto getIndividualDtoOfCompletedTasksWithinSearchPeriod(Employee employee,
"Модель отвечает за данные, которые хранятся и обрабатываются на сервере." Вот такая есть цитата в твоей статье

2024-03-27 09:29 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        return new IndividualAnalyticsResponseDto();
Понял)

2024-03-27 09:31 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    private IndividualAnalyticsResponseDto getIndividualDtoOfCompletedTasksWithinSearchPeriod(Employee employee,
Все верно, я к тому что если ты создаешь какой-то класс для переноса данных, то совершенно не обязательно его сохранять в БД.

2024-03-27 09:31 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        return new IndividualAnalyticsResponseDto();
Сделал

2024-03-27 09:33 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        for (Task task : employee.getTasks()) {
Так мне же надо проходить по сотрудникам, чтобы записывать их в лидеры или нарушители

2024-03-27 09:35 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    private IndividualAnalyticsResponseDto getIndividualDtoOfCompletedTasksWithinSearchPeriod(Employee employee,
Да, но я же помещаю этот класс в папку "model". Ты извини, что столько вопросов. Просто хочу понять, почему именно так правильно.

2024-03-27 12:24 UTC, JackobTheLion requested changes
Из общих рекомендаций я бы еще подумал над выделением отдельных контроллеров для статистики, не совсем корректно совать их в таски на мой взгляд.

2024-03-27 12:24 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +                if ((completedOnTime / employee.getTasks().size()) * 100 >
`completedOnTime * 100 / employee.getTasks().size())`
А вообще можно твоим методом воспользоваться

2024-03-27 12:24 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +                if (delayed != 0 && (delayed / employee.getTasks().size()) * 100 >
А зачем проверка на ноль?
0 / 50 * 100% = 0, ничего страшного нет.
И опять же можно твоим методом расчета процента воспользоваться

2024-03-27 12:24 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +                            calcPercent(teamCompletedOnTime, totalNumbersOfTaskOfTeamCompleted))
Влезает в одну строчку

2024-03-27 12:24 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +@PropertySource("classpath:application.yml")
Эта аннотация не нужна

2024-03-27 12:24 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +                            calcPercent(teamCompletedOnTime, totalNumbersOfTaskOfTeamCompleted))
Влезает в одну строку

2024-03-27 12:24 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    private int percentageOfTasksCompletedDelayed;
Лучше сделай leaderTrashhold и  laggyTrashhold

2024-03-27 12:28 UTC, Bervy commented on src/main/java/ru/epa/epabackend/mapper/AnalyticsIndividualMapper.java
> +public interface AnalyticsIndividualMapper {
Мне показалось, что разделить на 2 лучше, так как разные классы по смыслу.

2024-03-27 12:33 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        List<Employee> employees = employeeService.findAllByCreatorId(admin.getId());
Сделал

2024-03-27 12:34 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +                    .findAllByExecutorIdAndFinishDateBetween(employee.getId(), rangeStart, rangeEnd)) {
Я сделал рефактор метода, посмотри еще раз

2024-03-27 12:36 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +                    .findAllByExecutorIdAndFinishDateBetween(employee.getId(), rangeStart, rangeEnd)) {
Я сделал рефактор метода, посмотри еще раз

2024-03-27 12:46 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +                completedOnTime = 0;
Посмотри еще раз

2024-03-27 12:51 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +                            calcPercent(teamCompletedOnTime, totalNumbersOfTaskOfTeamCompleted))
Поправил

2024-03-27 13:21 UTC, Bervy commented on src/main/java/ru/epa/epabackend/controller/admin/TaskControllerAdmin.java
> +        return analyticsTeamMapper.mapToFullDto(analyticService
Сделал

2024-03-27 13:22 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    public IndividualAnalytics getIndividualStatistics(LocalDate rangeStart, LocalDate rangeEnd,
Сделал

2024-03-27 13:25 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    private IndividualAnalytics getIndividualDtoOfCompletedTasksWithinSearchPeriod(Employee employee,
Сделал

2024-03-27 13:28 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +                if ((completedOnTime / employee.getTasks().size()) * 100 >
Не совсем понял

2024-03-27 13:30 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +                if (delayed != 0 && (delayed / employee.getTasks().size()) * 100 >
Потому что у меня в условии меньше 40 процентов и когда будет получаться 0 то он будет записывать этого сотрудника как нарушителя

2024-03-27 13:42 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    private int percentageOfTasksCompletedDelayed;
Ок

2024-03-27 13:47 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +                if (delayed != 0 && (delayed / employee.getTasks().size()) * 100 >
Ок

2024-03-27 15:47 UTC, Bervy commented on src/main/java/ru/epa/epabackend/mapper/AnalyticsIndividualMapper.java
> +public interface AnalyticsIndividualMapper {
Эти аналитики отличаются, для чего их в один пихать???

2024-03-27 15:48 UTC, Bervy commented on src/main/java/ru/epa/epabackend/mapper/AnalyticsIndividualMapper.java
> +public interface AnalyticsIndividualMapper {
Разные модели и разные ДТО

2024-03-27 15:53 UTC, Bervy commented on src/main/java/ru/epa/epabackend/mapper/AnalyticsIndividualMapper.java
> +public interface AnalyticsIndividualMapper {
Почему мы EmployeeEvaluationMapper в EmployeeMapper не запихнули, хотя тоже относится к сотруднику? Потому что это разные модели и разный смысл.

2024-03-27 19:02 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/mapper/AnalyticsIndividualMapper.java
> +public interface AnalyticsIndividualMapper {
Оценка и сотрудник это совсем разные вещи. В EmployeeEvaluationMapper убери слово Employee и ничего не поменяется.
У тебя и то и то аналитика, просто одна группы, а другая индивидуальная. Все равно хочется сгруппировать и назвать просто AnalyticsMapper

2024-03-27 19:16 UTC, Bervy commented on src/main/java/ru/epa/epabackend/mapper/AnalyticsIndividualMapper.java
> +public interface AnalyticsIndividualMapper {
Мне кажется ты копаешься  уже в мелочах. Я не считаю свой вариант плохим, так же как твой имеет место быть.

2024-03-27 19:50 UTC, JackobTheLion requested changes

2024-03-27 19:50 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/controller/admin/AnalyticControllerAdmin.java
> +            @ApiResponse(responseCode = "204", description = "NO_CONTENT"),
Ошибка копипасты: 204 не может быть, должно быть 200

2024-03-27 19:50 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/controller/admin/AnalyticControllerAdmin.java
> +            @ApiResponse(responseCode = "409", description = "CONFLICT", content = @Content(
Аналогично, откуда конфликт при GET запросе. В остальных описаниях тоже

2024-03-27 19:50 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/dto/employee/EmployeeAnalyticsResponseDto.java
> +public class EmployeeAnalyticsResponseDto {
Только сейчас заметил. Уже есть ShortDto, он как раз для списков, используй лучше его.

2024-03-27 19:50 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    public TeamAnalytics getTeamStatsByAdmin(LocalDate rangeStart, LocalDate rangeEnd,
Влезет в одну строку

2024-03-27 19:50 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    public List<IndividualAnalytics> getIndividualStatsByAdmin(LocalDate rangeStart, LocalDate rangeEnd,
Влезет в одну строку

2024-03-27 19:50 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        List<Task> tasks = taskRepository.findAllByOwnerIdAndFinishDateBetween(employee.getCreator().getId(),
Все еще лишний запрос на админа. Ты можешь вытащить таски не по id админа, а по имейлу, который приходит в методе.

2024-03-27 19:50 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    private IndividualAnalytics getIndividualStats(Employee employee,
Влезет в одну строку

2024-03-27 19:50 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/mapper/AnalyticsIndividualMapper.java
> +public interface AnalyticsIndividualMapper {
Это не мелочь, это вопрос кодстайла. Твой вариант менее удачный, потому что ты дробишь класс там, где это не нужно делать. Вопрос зачем?

2024-03-27 20:08 UTC, Bervy commented on src/main/java/ru/epa/epabackend/dto/employee/EmployeeAnalyticsResponseDto.java
> +public class EmployeeAnalyticsResponseDto {
Я специально этот сделал, потому что еще email есть, который мне не нужен

2024-03-27 20:09 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    public TeamAnalytics getTeamStatsByAdmin(LocalDate rangeStart, LocalDate rangeEnd,
Сделал

2024-03-27 20:09 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    public List<IndividualAnalytics> getIndividualStatsByAdmin(LocalDate rangeStart, LocalDate rangeEnd,
Впритык, но влезло)

2024-03-27 20:11 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        List<Task> tasks = taskRepository.findAllByOwnerIdAndFinishDateBetween(employee.getCreator().getId(),
Так приходит email обычного сотрудника, а мне нужны все задачи команды

2024-03-27 20:11 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    private IndividualAnalytics getIndividualStats(Employee employee,
Исправил

2024-03-27 20:14 UTC, Bervy commented on src/main/java/ru/epa/epabackend/controller/admin/AnalyticControllerAdmin.java
> +            @ApiResponse(responseCode = "409", description = "CONFLICT", content = @Content(
Убрал

2024-03-27 20:15 UTC, Bervy commented on src/main/java/ru/epa/epabackend/mapper/AnalyticsIndividualMapper.java
> +public interface AnalyticsIndividualMapper {
Я это делаю, потому что это разные модели и ДТО.

2024-03-27 20:17 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/mapper/AnalyticsIndividualMapper.java
> +public interface AnalyticsIndividualMapper {
Ну и что? Убери слово командный и индивидуальный и суть не поменяется, это все еще аналитика. Сервис же один на все, контроллер один, по ДТО ты их не дробишь, почему тут нужно?

2024-03-27 20:18 UTC, Bervy commented on src/main/java/ru/epa/epabackend/controller/admin/AnalyticControllerAdmin.java
> +            @ApiResponse(responseCode = "204", description = "NO_CONTENT"),
API может также отправить 204 статус в ответ на GET запрос, чтобы указать, что запрошенный ресурс существует, но не имеет данных для добавления их в тело ответа.

2024-03-27 20:19 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/controller/admin/AnalyticControllerAdmin.java
> +            @ApiResponse(responseCode = "204", description = "NO_CONTENT"),
Так это не твой случай, у тебя тело ответа есть, ты возвращаешь его

2024-03-27 20:21 UTC, Bervy commented on src/main/java/ru/epa/epabackend/controller/admin/AnalyticControllerAdmin.java
> +            @ApiResponse(responseCode = "204", description = "NO_CONTENT"),
Хорошо

2024-03-27 20:22 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/dto/employee/EmployeeAnalyticsResponseDto.java
> +public class EmployeeAnalyticsResponseDto {
ок

2024-03-27 20:27 UTC, Bervy commented on src/main/java/ru/epa/epabackend/mapper/AnalyticsIndividualMapper.java
> +public interface AnalyticsIndividualMapper {
Хорошо, слил в один.

2024-03-27 20:43 UTC, JackobTheLion approved these changes

2024-03-28 04:16 UTC, ValentinaBuddha approved these changes

2024-03-28 05:19 UTC, merged

2024-04-02 08:17 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +    private int calcDelayedTasks(List<Task> tasks) {
Хорошо

2024-04-02 08:19 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        }
А то, что мне нужен Integer, мне в этом случае кастовать тогда?

2024-04-02 08:21 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +                if (calcPercent(completedOnTime, tasks.size()) > leaderTrashHold) {
Спасибо, опечатался)

2024-04-02 08:26 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        int totalNumbersOfTaskOfTeamCompleted = teamCompletedOnTime + teamDelayed;
Так tasks у каждого сотрудника отдельно, а это командная статистика.

2024-04-02 08:27 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +                if (delayed != 0 && calcPercent(delayed, tasks.size()) > violatorTrashHold) {
Да, раньше другая проверка была, поэтому была. Сейчас уже не нужно. Убрал.

2024-04-02 08:38 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +            if (task.getFinishDate().isAfter(task.getDeadLine())) {
Да, поправил

2024-04-02 08:41 UTC, Bervy commented on src/main/java/ru/epa/epabackend/repository/TaskRepository.java
> +            "WHERE (NULLIF((:status), NULL) IS NULL OR t.status = :status)" +
А если будет много фильтров, тогда как делать? Статус это просто один фильтр.

2024-04-02 08:52 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        List<Employee> employees = employeeService.findAllByCreatorEmail(email);
По поводу второго пункта, может я неправильно понимаю. Но у нас у каждого обычного сотрудника есть поле crator, которое ссылается на создателя этого сотрудника. Есть ли большая разница, что я буду брать email, а не ID создателя? Мы же просто в базе ссылаемся на создателя, где во всех записях надо будет еще что-то менять при смене почты?

2024-04-02 08:56 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        if (totalNumbersOfTaskOfTeamCompleted != 0) {
Хотя нет, эта проверка для того, если у нас нет ни одной задачи законченной, тогда есть ли смысл через билдер все эти поля заполнять? Или сразу вернуть новый объект TeamAnalytics.

2024-04-02 10:05 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +        List<Employee> employees = employeeService.findAllByCreatorEmail(email);
Так как админов может быть много, то я хочу тут найти только тех сотрудников, которых создал определенный админ.

2024-04-02 10:26 UTC, Bervy commented on src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
> +                    .findAllByExecutorIdAndFinishDateBetween(employee.getId(), rangeStart, rangeEnd);
Да у нас вообще предполагалось, что сотрудников не больше 10 у одного админа, но надо подумать как сделать лучше.