feat: add evaluations statistic and rating
employee-performance-assessment/epa_backend pull request #60
Opened 2024-03-27 20:05 UTC by BezuglovMikhail

2024-03-28 07:44 UTC, JackobTheLion requested changes

2024-03-28 07:44 UTC, JackobTheLion commented on src/main/resources/schema.sql
> +    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
Оставьте уже в покое несчастную схему с вот такими изменениями)

2024-03-28 07:44 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/RecommendationServiceImpl.java
> +    public List<Recommendation> findAll() {
Вообще всех? Такое точно нужно?

2024-03-28 07:44 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/dto/evaluation/EmployeeEvaluationResponseDto.java
> +    public EmployeeEvaluationResponseDto(Object name, Double score) {
А для чего такой странный конструктор? Ты его не используешь нигде, насколько я вижу.

2024-03-28 07:44 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/dto/recommendation/RecommendationResponseDto.java
> +    private String description;
Лучше не description а content или recomendation.

2024-03-28 07:44 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
> +        List<EmployeeEvaluation> employeeEvaluations = new ArrayList<>();
Укажи сразу размер массива:
`List<EmployeeEvaluation> employeeEvaluations = new ArrayList<>(evaluationRequestDtoList.size());`

2024-03-28 07:44 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
> +    public RatingResponseDto findRatingByAdmin(Long evaluatedId, LocalDate startDay, LocalDate endDay) {
Везде вместо id руководителя лучше использовать email, который можно в контроллере из партиципанта вытащить. Тогда можно упростить API не требуя этот самый id

2024-03-28 07:55 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/service/impl/RecommendationServiceImpl.java
> +    public List<Recommendation> findAll() {
Это для руководителя, получение всех рекомендаций сразу.

2024-03-28 07:56 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/controller/user/UserEmployeeEvaluationController.java
> +            @PathVariable("evaluatorId") Long evaluatorId,
я что-то видимо упустил, надо будет переделать. Буду использовать Participant.

2024-03-28 07:57 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/controller/admin/AdminRecommendationController.java
> +    public RecommendationResponseDto save(@PathVariable("senderId") Long senderId,
Согласен, переделаю.

2024-03-28 07:57 UTC, BezuglovMikhail commented on src/main/resources/schema.sql
> +    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
Верну всё в зад)

2024-03-28 07:59 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/dto/evaluation/EmployeeEvaluationResponseDto.java
> +    public EmployeeEvaluationResponseDto(Object name, Double score) {
Я его использую при получении усредненной статистики, когда возвращаю сотруднику оценки от его коллег.
Я сразу преобразую данные (название критериев и оценку) в EmployeeEvaluationResponseDto.

2024-03-28 08:00 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/dto/recommendation/RecommendationResponseDto.java
> +    private String description;
Хорошо исправлю на recomendation.

2024-03-28 08:01 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
> +        List<EmployeeEvaluation> employeeEvaluations = new ArrayList<>();
Ок, добавлю.

2024-03-28 08:02 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
> +    public RatingResponseDto findRatingByAdmin(Long evaluatedId, LocalDate startDay, LocalDate endDay) {
Согласен, поправлю везде в коде.

2024-03-28 15:43 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/dto/evaluation/EmployeeEvaluationResponseDto.java
> +    public EmployeeEvaluationResponseDto(Object name, Double score) {
Вообще не понял...
Ткни носом, где ты его используешь, я не увидел.

2024-03-28 15:45 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/controller/admin/AdminCriteriaController.java
> -        return criteriaMapper.mapToDto(criteriaService.create(criteriaRequestDto));
Ок

2024-03-29 04:44 UTC, ValentinaBuddha commented on src/main/java/ru/epa/epabackend/service/impl/CriteriaServiceImpl.java
>      public List<Criteria> findAll() {
Проверь транзакции. В методах получения  @Transactional(readOnly = true)

2024-03-29 04:44 UTC, ValentinaBuddha commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
>      public EmployeeEvaluation findById(Long evaluationEvaluationId) {
Проверь транзакции. В методах получения @transactional(readOnly = true)

2024-03-29 05:22 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/service/impl/RecommendationServiceImpl.java
> +    public List<Recommendation> findAll() {
да я так и хотел, ну допустим ты новый руководитель и хочешь понять больше про своих подчиненных, ты смотришь какие были рекомендации у твоих подчиненных и как они выросли.

2024-03-29 05:22 UTC, BezuglovMikhail commented on src/main/resources/schema.sql
> +    id             bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
исправлю.

2024-03-29 05:23 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
>      public EmployeeEvaluation findById(Long evaluationEvaluationId) {
исправлю

2024-03-29 06:00 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/controller/user/UserEmployeeEvaluationController.java
> +            @PathVariable("evaluatorId") Long evaluatorId,
Сделал!

2024-03-29 17:07 UTC, JackobTheLion requested changes

2024-03-29 17:07 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/repository/EmployeeEvaluationRepository.java
> +    List<EmployeeEvaluationResponseDto> findAllEvaluationsAdmin(@Param("email") String email);
Здесь и далее: по моему аннотация `@Param` не нужна, когда название параметра совпадает с ним же в запросе.
Если ее убрать, то дальше влезет в одну строку.
https://habr.com/ru/articles/440214/

2024-03-29 17:07 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/RecommendationServiceImpl.java
> +    public List<Recommendation> findAll() {
Так ты возвращаешь вообще все, даже не твоих подчинённых. Нужно делать выборку в репозитории по админу.

2024-03-30 04:45 UTC, ValentinaBuddha approved these changes

2024-03-30 09:37 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/controller/user/UserEmployeeEvaluationController.java
> +                .create(principal.getName(),
Сделал.

2024-03-30 09:41 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/controller/user/UserRecommendationController.java
> +        return recommendationMapper.mapList(recommendationService.findAllByRecipientEmail(recipientEmail));
Сделал.

2024-03-30 09:51 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/dto/evaluation/EmployeeEvaluationResponseDto.java
> +                        @ColumnResult(name = "score"),}))
Без аннотации тоже работает, убрал.

2024-03-30 09:52 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/service/impl/RecommendationServiceImpl.java
> +    public List<Recommendation> findAll() {
Выборка по админу есть, могу убрать метод.

2024-03-30 10:00 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/repository/EmployeeEvaluationRepository.java
> +    List<EmployeeEvaluationResponseDto> findAllEvaluationsAdmin(@Param("email") String email);
Убрал.

2024-03-30 12:56 UTC, JackobTheLion approved these changes

2024-03-30 14:27 UTC, merged

2024-04-02 06:23 UTC, nkorzh commented on src/main/java/ru/epa/epabackend/controller/user/UserRecommendationController.java
> +    public List<RecommendationResponseDto> findAllRecommendation(@PathVariable("recipientEmail") String recipientEmail) {
recommendation**s**

2024-04-02 06:23 UTC, nkorzh commented on src/main/java/ru/epa/epabackend/repository/EmployeeEvaluationRepository.java
> +    List<EmployeeEvaluationResponseDto> findAllEvaluationsUsers(String email);
так лучше не делать без крайней необходимости