feat: add methods evaluations and ratings
employee-performance-assessment/epa_backend pull request #85
Opened 2024-04-02 16:13 UTC by BezuglovMikhail

Добавлены методы:
1) получение сотрудником списка оцененных сотрудников с оценками по id анкеты.
2) получение сотрудником списка всех оцененных сотрудников с оценками.
3) получение сотрудником личного рейтинга (рассчитывается как средняя оценка за каждый месяц).
4) получение сотрудником командного рейтинга (рассчитывается как средняя оценка всех членов команды за каждый месяц).
5) получение админом командного рейтинга (рассчитывается как средняя оценка всех членов команды за каждый месяц).
6) получение админом списка индивидуальных рейтингов каждого сотрудника за каждый месяц.

В рейтинге на данный момент возвращается список из номера месяца и средней оценки.

2024-04-02 18:12 UTC, JackobTheLion requested changes

2024-04-02 18:12 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
> +        Employee employee = employeeService.findByEmail(adminEmail);
Если тебе тут не нужен админ, а нужен только его id, то может его сразу и запросить? Или еще лучше сразу искать в employeeEvaluationRepository по имейлу админа

2024-04-02 18:12 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
> +            List<ResponseRatingFullDto> ratingForMonth = employeeEvaluationRepository
Тоже можно сразу запрашивать у БД весь список рейтингов, а не по одному.

2024-04-03 10:02 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
> +            if (!myEmployeeEvaluations.contains(responseMyEmployeeEvaluationsDto)) {
Метод возвращает все поставленные оценки сотрудника из всех его заполненных анкет. Оценки хранятся в одной таблице, когда собираем оценки их нужно фильтровать по id анкеты.
На созвоне мы обсуждали, что не нужно выдавать весь список. 
Возможно следует разбить метод на два. 1 будет возвращать список оцененных коллег, а 2 будет возвращать список оценок выбранного колеги.

2024-04-03 10:04 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
> +        Employee employee = employeeService.findByEmail(adminEmail);
Возможно я напутал с реализацией, когда тестировал реализацию по email метод выдавал не верный результат.
Я перепроверю.

2024-04-03 10:06 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
> +        assert employee.getCreator() != null;
Спасибо, поправлю.

2024-04-03 10:10 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
> +            List<ResponseRatingFullDto> ratingForMonth = employeeEvaluationRepository
Мне нужно запросить индивидуальный рейтинг за несколько месяцев для всех сотрудников, то есть я запрашиваю список рейтингов для каждого сотрудника.
Я если честно не сообразил как это сделать одним запросом.

2024-04-03 10:11 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
> +    private List<ResponseMyEvaluationsDto> sortMyEvaluations(List<EmployeeEvaluation> evaluations) {
Да согласен, фильтр больше подходит.

2024-04-03 19:14 UTC, OsipovKonstantin requested changes

2024-04-03 19:14 UTC, OsipovKonstantin commented on src/main/java/ru/epa/epabackend/controller/admin/AdminRecommendationController.java
>      }
Комментарий к классу UserRecommendationController. Первый эндпоинт получает список, а мы в рамках одной анкеты запрашиваем одну рекомендацию. Необходимо добавить questionnaireId и вместо списка возвращать один элемент.
Эндпоинт же посвящен этой странице, правильно?
![image](https://github.com/employee-performance-assessment/epa_backend/assets/98541812/13b60192-dd35-43de-8d22-8ac205b36c8b)

2024-04-03 19:14 UTC, OsipovKonstantin commented on src/main/java/ru/epa/epabackend/controller/admin/AdminRecommendationController.java
>      }
Второй эндпоинт в классе UserRecommendationController - запрос рекомендации по id рекомендации. В макетах этого нет. Необходимо удалить, чтобы не было лишнего кода

2024-04-04 14:22 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/controller/admin/AdminEmployeeEvaluationController.java
> +    }
У руководителя, тоже есть доступ к командной и индивидуальной статистикой каждого сотрудника.

2024-04-04 17:16 UTC, OsipovKonstantin commented on src/main/java/ru/epa/epabackend/controller/admin/AdminEmployeeEvaluationController.java
> +    }
Это имело бы смысл, если бы мы хотели посмотреть командный рейтинг чужого сотрудника. У своего сотрудника командный рейтинг такой же, что если бы админ посмотрел командный рейтинг для себя в user controller. Но если с заделом на будущее, где можно будет чужие команды смотреть, то да

2024-04-04 22:02 UTC, OsipovKonstantin requested changes

2024-04-04 22:32 UTC, OsipovKonstantin commented
Не хватает эндпоинтов:
1. получение рейтинга за предыдущий месяц, который отображается в шапке профиля сотрудника. В дизайне это Личный кабинет -> вверху справа
2. получение среднего рейтинга за анкету (и в админе - по id сотрудника, и в user controller'e - по principal'у). В дизайне это Личный кабинет -> раздел Оценки -> нажимаем на одну из фиолетовых строк и попадаем внутрь оценки -> сверху в шапке высвечивается средний рейтинг за анкету
3. получение оценок по конкретной анкете (в админе - по principal'у, id сотрудника, которого оценили, и id анкеты. В user controller'е - по principal'у, id сотрудника, которого оценили, и id анкеты). В дизайне это находится в Оценка ЭС (Оцени коллегу) -> раздел Оценка поставлена -> нажимаем на фиолетовую строку -> внизу 1 столбец со звёздами по этой анкете и внизу рекомендация (у админа) и внизу нет рекомендации (когда оценил сотрудник)

2024-04-05 05:36 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/controller/admin/AdminEmployeeEvaluationController.java
> +    }
Тут задумка как я понял:
1. Сотрудник заходит в ЛК и может посмотреть рейтинг команды за каждый месяц и свой.
2. Админ когда заходит в свой ЛК может посмотреть Командный рейтинг, а в личном он видит рейтинг каждого сотрудника по месяцам. 
По крайней мере я так понял Викторию.

2024-04-05 05:45 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/controller/admin/AdminEmployeeEvaluationController.java
> +    }
ResponsePersonalRatingDto я возвращаю список (короткую информацию о сотруднике и список его рейтинга помесячно).
![image](https://github.com/employee-performance-assessment/epa_backend/assets/115709844/a83c0368-8ebc-4a9e-9726-8c4908b4a9b3)

2024-04-05 05:46 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/controller/admin/AdminEmployeeEvaluationController.java
> +    }
Если нет рейтинга, значит сотрудника не оценивали.

2024-04-05 05:47 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/controller/admin/AdminRecommendationController.java
>      }
Согласен добавлю проверки.

2024-04-05 05:53 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/controller/user/UserEmployeeEvaluationController.java
Я не вижу эти строке, я переделал уту часть. Напиши про что ты говоришь?

2024-04-05 05:56 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/controller/user/UserEmployeeEvaluationController.java
> +    }
да, я тоже об этом подумал, добавлю.

2024-04-05 05:58 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/repository/EmployeeEvaluationRepository.java
> +    List<ResponseRatingFullDto> findCommandRating(Long adminId);
да ты прав, поправлю.

2024-04-05 06:00 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/repository/EmployeeEvaluationRepository.java
> +    List<ResponseRatingFullDto> findPersonalRating(String email);
Группировку поправлю, год тоже буду выводить.

2024-04-05 16:52 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/controller/admin/AdminEmployeeEvaluationController.java
>      }
согласен убрал.

2024-04-05 18:32 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/controller/user/UserEmployeeEvaluationController.java
> +    }
Сделаю в следующем ПР.

2024-04-05 18:46 UTC, OsipovKonstantin approved these changes

2024-04-05 19:15 UTC, JackobTheLion approved these changes

2024-04-05 19:16 UTC, merged