feat(questionnaire): add endpoint update last questionnaire with defa…
employee-performance-assessment/epa_backend pull request #89
Opened 2024-04-03 13:22 UTC by OsipovKonstantin

Добавление эндпоинта, где мы обновляем последнюю анкету с критериями по умолчанию

2024-04-03 13:51 UTC, BezuglovMikhail approved these changes

2024-04-03 13:51 UTC, JackobTheLion requested changes

2024-04-03 13:51 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/impl/QuestionnaireServiceImpl.java
> +        questionnaire.setCriterias(new ArrayList<>(criteriaService.findDefault()));
А зачем new ArrayList? Можно просто
`questionnaire.setCriterias(criteriaService.findDefault());`

2024-04-03 14:04 UTC, JackobTheLion approved these changes

2024-04-03 14:04 UTC, merged

2024-04-08 16:36 UTC, nkorzh reviewed
все ок