feat: add mapstruct.
employee-performance-assessment/epa_backend pull request #9
Opened 2024-03-01 07:21 UTC by BezuglovMikhail

2024-03-01 07:54 UTC, JackobTheLion requested changes
Еще я бы немного переработал названия методов в мапперах и убрал из них названия сущностей, оставив только mapToFullDto(), mapToEntity() и т.д.. Маппер будет бином, поэтому к его методам ты будешь обращаться через имя поля следующим образом
`taskMapper.mapToDto(task)`
т.о. будет понятно, что и во что ты маппируешь и имя метода можно сократить

2024-03-01 07:54 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/mapper/EmployeeMapper.java
> +    default String setFullName(Employee employee) {
Кажется решили, что имя будет одной строкой и мы бить не будем

2024-03-01 07:54 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/mapper/TaskMapper.java
> +    ProjectMapper INSTANCE_ = Mappers.getMapper(ProjectMapper.class);
Инстансы не нужны, ты же пометил, что он должен быть бином. Теперь его можно инжектить

2024-03-01 07:54 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/mapper/TaskMapper.java
> +    TaskFullDto taskUpdateToOutDto(Task task);
В TaskFullDto есть сущности EmpoyeeDto и ProjectDto, их тоже нужно маппить. Сейчас мапстракт не знает, куда смотреть. Для того, чтобы все заработало нужно дописать в аннотации:
`@Mapper(componentModel = "spring", uses = {ProjectMapper.class, EmployeeMapper.class})`

2024-03-01 07:54 UTC, JackobTheLion commented on src/main/java/ru/epa/epabackend/service/EmployeeServiceImpl.java
> +    EmployeeMapper employeeMapper;
Private final и лишняя строчка

2024-03-01 13:19 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/mapper/EmployeeMapper.java
> +    default String setFullName(Employee employee) {
я не стал менять логику, заменил только DTO.
В принципе раз решили то давай сразу поправлю.

2024-03-02 05:43 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/mapper/TaskMapper.java
> +    ProjectMapper INSTANCE_ = Mappers.getMapper(ProjectMapper.class);
Сделал.

2024-03-02 05:44 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/mapper/TaskMapper.java
> +    TaskFullDto taskUpdateToOutDto(Task task);
Сделал.

2024-03-02 05:45 UTC, BezuglovMikhail commented on src/main/java/ru/epa/epabackend/service/EmployeeServiceImpl.java
> +    EmployeeMapper employeeMapper;
убрал.

2024-03-03 12:34 UTC, JackobTheLion approved these changes

2024-03-03 21:36 UTC, ValentinaBuddha approved these changes

2024-03-05 05:02 UTC, merged